apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/service: "http://k8s-example-vault.vault.svc.cluster.local:8200"
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/myapp"
        vault.hashicorp.com/agent-inject-default-template: json
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: ghcr.io/maciejwojs/k8s-example-backend:0.0.29
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
