apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: k8s-example
data:
  DEVELOPMENT: "true"
  #! EXTERNAL JOB does migrations and seeding, so we don't want to do it in the backend container
  PERFORM_DATABASE_MIGRATIONS: "false"
  PERFORM_DATABASE_SEEDING: "false"
  