# DATABASE_URL: vault kv put secret/seed DATABASE_URL='...'
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-database
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: seed-sa
      restartPolicy: Never
      ttlSecondsAfterFinished: 120
      containers:
        - name: seed-db
          image: ghcr.io/maciejwojs/k8s-example-backend:0.0.25
          command: ["bun"]
          args:
            - seed
          envFrom:
            - configMapRef:
                name: seed-config
