# DATABASE_URL: vault kv put secret/seed DATABASE_URL='...'
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-database
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: "seed"
        vault.hashicorp.com/service: "http://k8s-example-vault.vault.svc.cluster.local:8200"
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/seed"
        vault.hashicorp.com/agent-inject-default-template: json
    spec:
      serviceAccountName: seed-sa
      restartPolicy: Never
      ttlSecondsAfterFinished: 120
      containers:
        - name: seed-db
          image: ghcr.io/maciejwojs/k8s-example-backend:0.0.30
          command: ["bun"]
          args:
            - seed
          envFrom:
            - configMapRef:
                name: seed-config
