apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrate-sa
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
