apiVersion: v1
kind: ServiceAccount
metadata:
  name: seed-sa
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-config
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  USE_VAULT: "true"
  VAULT_ADDR: http://k8s-example-vault.vault.svc.cluster.local:8200
  VAULT_ROLE: seed
  VAULT_SECRET_PATH: secret/data/seed