apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-config
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  DEVELOPMENT: "true"
  PERFORM_DATABASE_MIGRATIONS: "false"
  PERFORM_DATABASE_SEEDING: "false"
  