apiVersion: batch/v1
kind: Job
metadata:
  name: atlas-migrate
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      ttlSecondsAfterFinished: 120
      containers:
        - name: atlas
          image: ghcr.io/maciejwojs/k8s-example-backend:0.0.11
          command: ["atlas"]
          args:
            - migrate
            - apply
            - --env
            - local
            - --url
            - $(DATABASE_URL)?sslmode=disable
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
