# This job is used to run the database migrations before the application is deployed. 
# It is configured to run as a PreSync hook in ArgoCD, ensuring that the migrations are applied before the application is updated. 
# The database connection URL is retrieved from a Kubernetes secret named 'backend-secret'.
apiVersion: batch/v1
kind: Job
metadata:
  name: atlas-migrate
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      ttlSecondsAfterFinished: 120
      containers:
        - name: atlas
          image: ghcr.io/maciejwojs/k8s-example-backend:0.0.11
          command: ["atlas"]
          args:
            - migrate
            - apply
            - --env
            - local
            - --url
            - $(DATABASE_URL)?sslmode=disable
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
---
# This job is used to seed the database with initial data. 
# It runs after the migration job and is also a PreSync hook in ArgoCD. 
# The job will run the "bun seed" command to populate the database with sample data.
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-database
  namespace: k8s-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      ttlSecondsAfterFinished: 120
      containers:
        - name: seed-db
          image: ghcr.io/maciejwojs/k8s-example-backend:0.0.11
          command: ["bun"]
          args:
            - seed
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: DEVELOPMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DEVELOPMENT
            - name: PERFORM_DATABASE_SEEDING
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PERFORM_DATABASE_SEEDING