apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-example-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MaciejWojs/k8s-example-iac.git
    targetRevision: HEAD
    path: infrastructure
    directory:  
      exclude: '*secret-example*.yaml'
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-example
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      refresh: true
    automated:
      enabled: true
      prune: true
      selfHeal: true