apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: migrate
  namespace: vault-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  authentication:
    path: kubernetes
    role: policy-admin
    serviceAccount:
      name: vault-config-admin
  policy: |
    path "secret/data/migrate" {
      capabilities = ["read"]
    }
